debug-mode: false                 # enable debug particles

snapshot-refresh-interval: 12000  # ticks between chunk snapshot refresh, won't change without restart
engine-rate: 1                    # 1 = every tick; 2 = every other tick; 3 = every third tick; etc.
recheck-interval: 20              # ticks between forced rechecks for visible entities

always-show-radius: 16             # radius to always show entities
raycast-radius: 64                # beyond this, entities auto-hide
max-occluding-count: 3            # blocks before blocking
search-radius: 128                 # search radius for entities

octree-max-entities: 16           # maximum entities in octree before it splits
octree-max-depth: 64
octree-world: world               # The world to cull entities in
octree-min:                       # world minimum to cull entities in, set to 0 to disable
  x: -136
  y: 33
  z: -270
octree-max:                       # world maximum to cull entities in, set to 0 to disable
  x: 403
  y: 144
  z: 251